---
title: "Datos espaciales"
date: "`r Sys.Date()`"
lang: es
execute:
  echo: true
  output: true
  eval: true
  cache: true
format:
  html:
    toc: true
    toc-location: left
    toc-title: "Contenidos"
    embed-resources: true
    theme: cosmo
    code-fold: false
    code-tools: true
    df-print: paged
    include-in-header:
      text: |
        <style>
        body {
          text-align: justify;
        }
        </style>
---

# ¿De qué trata la clase de hoy?

Hoy vamos a visualizar datos espaciales. La idea es la siguiente:

1.  Estructura de los datos espaciales: sistema de referencia

------------------------------------------------------------------------

## Librerías necesarias

```{r}
#| label: load-packages
#| message: false
#| warning: false
#| cache: false

# Instalamos pacman si no está disponible
if (!require("pacman")) install.packages("pacman")

pacman::p_load(
  tidyverse,    # manipulación y visualización de datos
  here,         # gestión de rutas relativas
  scales,       # formateo de ejes y etiquetas
  janitor,      # limpieza de nombres
  patchwork,     # organizar el apilado de figuras
  geobr,
  sf,
  rnaturalearth, 
  rnaturalearthdata, 
  geodata, 
  osmdata,
  tidygeocoder, 
  cartogram, 
  geofacet, 
  statebins, 
  leaflet, 
  ggrepel,
  geoAr
)
```

------------------------------------------------------------------------

## Preparación de los datos

Vamos a utilizar nuevamente los datos de Brasil. TODO texto que justifique la eleccion y todas las posibles visualizaciones que podremos hacer.

```{r}
#| label: cargar-datos
#| message: false
#| warning: false

# ----------------------------------------------------------
# Cargamos todas las fuentes de datos individuales

df_elections      <- readRDS(here("09_tutorial/data/elections.rds"))
df_finance        <- readRDS(here("09_tutorial/data/finance.rds"))
df_transfers      <- readRDS(here("09_tutorial/data/transfers_combined.rds"))
df_socioeconomic  <- readRDS(here("09_tutorial/data/socioeconomic.rds"))
df_municipalities <- readRDS(here("09_tutorial/data/municipalities.rds"))
```

```{r}
data_frames <- list(
  df_elections, df_finance, df_transfers, df_socioeconomic, df_municipalities
)
for (i in 1:length(data_frames)) {
  print(head(data_frames[[i]]))
# }
```
